- name: Install and run nginx
  become: yes
  hosts: all
  gather_facts: false
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: installed

    - name: starting and enabled
      ansible.builtin.service:
        name: nginx
        state: started
