- name: variables from prompt
  hosts: mongodb
  vars_prompt:
    - name: USERNAME
      prompt: "Please enter your USERNAME"
      private: no
    - name: PASSWRD
      prompt: "Please enter your PASSWRD"
      private: yes
  tasks:
    - name: print variable values
      ansible.builtin.debug:
        msg: "username: {{ USERNAME }}, password: {{ PASSWRD }}"
