- name: add the user
  hosts: all
  tasks:
  - name: checking the user exists or not
    ansible.builtin.command: id gsp
    register: output
    ignore_errors: true
  
  - name: adding the user based on above command
    ansible.builtin.user:
      name: gsp
    when: output.rc != 0
    become: yes